Rum 18631 mandatory fields
keysight-eggplant/real-user-data-sdk-js pull request #16
Opened 2019-04-01 16:05 UTC by MalcolmSmithUK

2019-04-04 09:21 UTC, robertdumitrescu commented on tests/rci.spec.js
> +const localStorageClientIdKey = "eggplantRciClientId";
Port the tests from mocha/chai to jest

2019-04-04 10:02 UTC, robertdumitrescu approved these changes

2019-04-04 10:21 UTC, yghern requested changes

2019-04-04 10:21 UTC, yghern commented on src/collectors/utility/uuid.js
> +    ii;
[FORMAT] strange line break

2019-04-04 10:21 UTC, yghern commented on src/core/Collector.js
> +/* eslint no-await-in-loop: 0 */
why this file is exception from eslint rule? is there no other way?

2019-04-04 10:21 UTC, yghern commented on tests/rci.spec.js
> +        expect(window.assertOnMe.journeyAction).equal('stop');
We have global now for journey action (JOURNEY_ACTION)

2019-04-05 14:14 UTC, yghern approved these changes

2019-04-08 13:08 UTC, merged